# Definimos el SO
FROM ubuntu:16.04
# Instalamos apache para centos (S.O.)
RUN apt-get update
RUN apt-get install apache2 -y
# `docker build --tag apache-ubuntu .`
# Nota no olvidar el punto final del comando 
# para referenciar el Docker file del directorio
# `docker images` para ver el listado de imagenes creadas