FROM nginx

# LABEL version=1
# RUN echo "1" >> /usr/share/nginx/html/test.txt
# RUN echo "2" >> /usr/share/nginx/html/test.txt
# RUN echo "3" >> /usr/share/nginx/html/test.txt

LABEL version=2
RUN \
    echo "1" >> /usr/share/nginx/html/test.txt && \
    echo "2" >> /usr/share/nginx/html/test.txt && \
    echo "3" >> /usr/share/nginx/html/test.txt